server:
  port: 12345

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/profiler
    username: kid
    password: root
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration

encryption:
  xxhash:
    seed: KCd6PwNaNjsNt6YR